language: ruby
rvm:
- 2.3.1
- 2.3.3
- 2.4.0
cache: bundler
sudo: true
before_script:
- bash .travis.install-mysql-5.7.sh
script:
- bundle exec rails db:create
- bundle exec rails db:migrate
- bundle exec rake
notifications:
  slack:
    secure: uBRqaLgPzU1pwlPRD+efeZMbi9hgjNtyw63tJZXsO7aBFSZ97yP5sN/KmIG2rhUG5lwQzeODn0PRqktqj/RuW9eViFve+ZzSonjZRRHpjs6gOP4OEiW50e8xKUagQwBTpsJgXT/cH4WQP5XJNEeSi4SJGizUxzSniRo7dXrbSDDkpontQHPNzHDf49r8EKG9Q8tQKm9ss9v18oiUL47pZugs1xeMOlrzX3VKJFNc4uEir28NwINuWX/Fd/vjCMVqSyZff0UWyHfBF9zwgc4MxwM/Ch73M7FLJsr5BxCYytGDxc8CGWbLiT/CT9sMC1AUztNbvvUm/7HNH5AoOOohWnESpUpnl8tNJ7U8dCyIKVuCxWygqz6WktoVLFREV8f8h/nic66o+XelyLpBfhfVPXz2+YHjgxclHDgScSulrr3IGb1+C51wSFWxz0hbq83BGoWBRHgk6txdjv3s4Vpix9oNQumMDzu1W5Cvn3lh0qfYTs6H/2TKPQ8M5jxgvmGq31RdvseN4GxaDmvF5keXnirVH1WbKW06Qyd2lRuz7MnDyPWVBcXtnig13Y5LM9qdBsxgUp1oxXWAtyyMyI0upEV6op08yMFdgEsDemkrWeBk6g/w04oLbJ/tenrmtvz7KBy+dmmiL++lM423O1vLDl2/lm12MRgmTUyqrYjh/dI=
